[config]

[config.wallpaper]
set = true
command = "awww img {{image}} --transition-type wipe --transition-duration 1"

[templates.kitty]
input_path = '~/Projects/lopshell/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors-matugen.conf'

[templates.gtk3]
input_path = '~/Projects/lopshell/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/Projects/lopshell/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.hypr]
input_path = '~/Projects/lopshell/matugen/templates/hypr-colors.lua'
output_path = '~/.config/hypr/config/colors.lua'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/Projects/lopshell/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar || true'