-- AUTOGENERATED BY MATUGEN. Не редактировать руками.

-- Основная палитра.
LSH_PRIMARY    = "rgba(bcc2ffff)"
LSH_ON_PRIMARY = "rgba(252b61ff)"
LSH_SECONDARY  = "rgba(c4c5ddff)"
LSH_TERTIARY   = "rgba(e7b9d6ff)"
LSH_SURFACE    = "rgba(131318ff)"
LSH_SURFACE_HI = "rgba(29292fff)"
LSH_ON_SURFACE = "rgba(e4e1e9ff)"
LSH_OUTLINE    = "rgba(91909aff)"
LSH_ERROR      = "rgba(ffb4abff)"

-- Полупрозрачные варианты.
LSH_OUTLINE_DIM = "rgba(91909a55)"

-- Совместимость со старыми конфигами CachyOS.
CACHYLGREEN = LSH_PRIMARY
CACHYMGREEN = LSH_SECONDARY
CACHYDGREEN = LSH_TERTIARY
CACHYLBLUE  = LSH_SECONDARY
CACHYMBLUE  = LSH_SURFACE_HI
CACHYDBLUE  = LSH_SURFACE
CACHYWHITE  = LSH_ON_SURFACE
CACHYGREY   = LSH_ON_SURFACE
CACHYGRAY   = LSH_OUTLINE