-- AUTOGENERATED BY MATUGEN. Не редактировать руками.

-- Основная палитра.
LSH_PRIMARY    = "rgba({{colors.primary.default.hex_stripped}}ff)"
LSH_ON_PRIMARY = "rgba({{colors.on_primary.default.hex_stripped}}ff)"
LSH_SECONDARY  = "rgba({{colors.secondary.default.hex_stripped}}ff)"
LSH_TERTIARY   = "rgba({{colors.tertiary.default.hex_stripped}}ff)"
LSH_SURFACE    = "rgba({{colors.surface.default.hex_stripped}}ff)"
LSH_SURFACE_HI = "rgba({{colors.surface_container_high.default.hex_stripped}}ff)"
LSH_ON_SURFACE = "rgba({{colors.on_surface.default.hex_stripped}}ff)"
LSH_OUTLINE    = "rgba({{colors.outline.default.hex_stripped}}ff)"
LSH_ERROR      = "rgba({{colors.error.default.hex_stripped}}ff)"

-- Полупрозрачные варианты.
LSH_OUTLINE_DIM = "rgba({{colors.outline.default.hex_stripped}}55)"

-- Совместимость со старыми конфигами CachyOS.
CACHYLGREEN = LSH_PRIMARY
CACHYMGREEN = LSH_SECONDARY
CACHYDGREEN = LSH_TERTIARY
CACHYLBLUE  = LSH_SECONDARY
CACHYMBLUE  = LSH_SURFACE_HI
CACHYDBLUE  = LSH_SURFACE
CACHYWHITE  = LSH_ON_SURFACE
CACHYGREY   = LSH_ON_SURFACE
CACHYGRAY   = LSH_OUTLINE